package cc.common.mod;

import cc.common.init.CoreBlocks;
import cc.common.init.CoreItems;
import cc.common.init.CoreRecipes;
import cc.common.init.CoreResearch;
import cc.common.world.CCWorldGen;
import cc.network.proxy.CommonProxy;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import cc.utils.cfg.Config;

import java.io.File;
import java.util.ArrayList;

/**
 * Created by jakihappycity on 05.11.15.
 */
@Mod(modid = CCCore.modid, version = CCCore.version, name = CCCore.name)
public class CCCore {

    public static final String modid = "cc";
    public static final String version = "1.0.1710.0";
    public static final String name = "ChromaCraft";

    public static final String clientProxy = "cc.network.proxy.ClientProxy", serverProxy = "cc.network.proxy.CommonProxy";

    public static final Logger log = LogManager.getLogger("ChromaCraft");

    public static CreativeTabs tabCC = new CreativeTabs(CreativeTabs.getNextID(), "chromacraft") {
        @Override
        public Item getTabIconItem() {
            return CoreItems.chromaticum;
        }

        @Override
        public String getTabLabel() {
            return "ChromaCraft";
        }

        @Override
        public String getTranslatedTabLabel() {
            return "ChromaCraft";
        }
    };

    public File modDir;

    @SidedProxy(clientSide = clientProxy, serverSide = serverProxy)
    public static CommonProxy proxy;

    public static CCCore instance;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        log.debug("Loading " + name);
        instance = this;
        ModInfo(event.getModMetadata());
        this.modDir = event.getModConfigurationDirectory();
        try {
            Config.initialize(event.getSuggestedConfigurationFile());
        } catch (Exception e) {
            log.error("ChromaCraft has a problem loading it's configuration");
        } finally {
            if(Config.config != null) {
                Config.save();
            }
        }
        CoreBlocks.Init();
        CoreItems.Init();
        CoreRecipes.Init();
        CoreResearch.Init();
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event)
    {

    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
        log.debug(name + " has loaded");
        GameRegistry.registerWorldGenerator(new CCWorldGen(), 16);
    }

    public static void ModInfo(ModMetadata m)
    {
        m.autogenerated = false;
        m.modId = modid;
        m.version = version;
        m.name = name;
        ArrayList<String> authors = new ArrayList<String>();
        authors.add("JakiHappyCity");
        m.authorList = authors;
        m.logoFile = "logo.png";
    }

}
